### PR TITLE
Add Simplify function

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by fredj** [comment]
LGTM

**Comment by sbrunner** [comment]
Thanks, can You merge it? Actually I don't have the commit rights :-)

**Comment by fredj** [comment]
Neither do I !

**Comment by tsauerwein** [comment]
And I think I don't have the rights to add you.

**Comment by sbrunner** [comment]
Thanks @tsauerwein I will have a look :-)

**Comment by tsauerwein** [comment]
Thanks for updating! Travis fails, but I am not sure if it worked before?

**Comment by sbrunner** [comment]
Yes but some times ago ...
I will have a look layer ...
Thanks @tsauerwein :-)

**Comment by elemoine** [comment]
> And I think I don't have the rights to add you.

But you do have write access to the repo (all the repos of the geoalchemy organization).

Feel free to merge this when the Travis build is fixed.

**Pull request closed without merging**
